(() => {
  const menu = document.querySelector('#menu');
  const nav = document.querySelector('#nav');
  const langButtons = [...document.querySelectorAll('[data-lang]')];
  const navGroups = [...document.querySelectorAll('.nav-group')];

  const copy = {
    en: {
      'utility.network':'PROPTECHUSA.AI PROPERTY INTELLIGENCE NETWORK','utility.status':'SPAIN · CERTIFICATION IN PROGRESS',
      'nav.product':'Product','nav.data':'Spain Data','nav.developers':'Developers','nav.network':'Global Network','nav.docs':'Docs','nav.dashboard':'Dashboard','nav.access':'Launch access',
      'mega.productLabel':'SPAIN PROPERTY GRAPH','mega.graph':'Property graph','mega.graphCopy':'Identity, addresses, buildings and parcel geometry.','mega.arch':'Architecture','mega.archCopy':'How official source data becomes governed infrastructure.','mega.controlLabel':'CONTROL LAYER','mega.governance':'Governance','mega.governanceCopy':'Fail-closed identity, drift evidence and promotion gates.','mega.useCases':'Use cases','mega.useCasesCopy':'Product, AI, mapping, diligence and enterprise workflows.',
      'mega.coverageLabel':'AUTHORITY MODEL','mega.coverage':'Coverage','mega.coverageCopy':'DGC common territory and separate foral systems.','mega.sources':'Sources','mega.sourcesCopy':'Catastro CP, AD, BU and non-protected detail.','mega.identityLabel':'IDENTITY','mega.refcatCopy':'Durable referencia catastral joins.','mega.protected':'Protected-data boundary','mega.protectedCopy':'Ownership and individualized cadastral value stay outside the open contract.',
      'mega.docs':'Spain Docs','mega.docsCopy':'Country contract, routes, identity and coverage.','mega.restCopy':'Server-side PropData delivery with country=ES.','mega.dashboard':'Customer Dashboard','mega.dashboardCopy':'Keys, usage, Request Lab, MCP and billing.','mega.mcpCopy':'AI-native access through the separate OAuth flow.','mega.spainStatus':'Catastro · certifying','mega.allCountries':'Explore global coverage →',
      'hero.status':'SPAIN LAUNCH CERTIFICATION IN PROGRESS','hero.eyebrow':'PROPDATA SPAIN · COUNTRY-NATIVE PROPERTY INFRASTRUCTURE','hero.title':'Spain’s cadastre,<br>normalized for software.','hero.lede':'PropData is turning authoritative cadastral parcels, addresses, buildings and cadastral references into one deterministic Spanish property graph — built for product teams, AI systems and enterprise workflows.','hero.cta1':'Explore the Spain graph','hero.cta2':'Read launch docs',
      'proof.label':'SOURCE SYSTEM SCALE','proof.records':'official cadastral real-estate records administered by DGC','proof.families':'parcels · addresses · buildings','proof.crs':'source-native spatial reference','proof.id':'cadastral reference identity','proof.governance':'governed resolution','proof.note':'78.9M is official DGC source-system scale, not a claim that every record has already been promoted into PropData.',
      'signal.common':'Common-territory certification','signal.foral':'Foral systems handled separately',
      'platform.eyebrow':'THE PRODUCT','platform.title':'The routes are the doorway.<br>The Spanish property graph is the product.','platform.copy':'Spain is not a flat parcel file. A useful property layer has to preserve cadastral reference identity, municipality context, addresses, parcel geometry, building relationships, source revisions and coverage states without pretending protected or unavailable facts exist.',
      'cap1.title':'Cadastral identity','cap1.copy':'Resolve and preserve the referencia catastral as a durable Spanish property identifier.','cap2.title':'Address graph','cap2.copy':'Attach official Catastro address identities without flattening away source semantics.','cap3.title':'Parcel geometry','cap3.copy':'Carry authoritative cadastral parcel boundaries with the source, revision and spatial contract.','cap4.title':'Building relationships','cap4.copy':'Connect buildings and building parts to cadastral property identity where the official graph supports it.','cap5.title':'Coordinate resolution','cap5.copy':'Turn latitude / longitude into property context only where promoted geometry supports a deterministic answer.','cap6.title':'Municipality routing','cap6.copy':'Normalize thousands of municipality-scoped source packages behind one country contract.','cap7.title':'Provenance','cap7.copy':'Keep source family, municipality, source revision and evidence lineage with property facts.','cap8.title':'Protected-data boundary','cap8.copy':'Ownership and cadastral value stay outside the open-data contract unless a lawful, separately entitled source exists.','cap9.title':'Coverage semantics','cap9.copy':'A property match, geometry match and dataset-coverage state are separate signals — because they mean different things.','cap10.title':'Quality gates','cap10.copy':'Ambiguity, source drift and unresolved identity fail closed instead of silently becoming fake certainty.','cap11.title':'AI-native delivery','cap11.copy':'The same governed graph can serve REST, OAuth MCP, bulk and custom enterprise workflows.','cap12.title':'Country control plane','cap12.copy':'Spain fits the same PropData operating model as the U.S., UK, New Zealand, Australia and Estonia.',
      'architecture.eyebrow':'FROM CATASTRO TO PRODUCT INFRASTRUCTURE','architecture.title':'One property request.<br>A governed chain underneath it.','architecture.copy':'The hard part is not serving JSON. It is resolving the correct cadastral authority, preserving native identity, joining official source families, classifying drift and returning only facts the evidence supports.',
      'pipe1.title':'Resolve input','pipe1.copy':'Address, coordinates or cadastral identity enter one country contract.','pipe2.title':'Route authority','pipe2.copy':'DGC common territory or the correct separate foral system.','pipe3.title':'Connect graph','pipe3.copy':'REFCAT joins parcel, address, building and non-protected property context.','pipe4.title':'Govern evidence','pipe4.copy':'Coverage, source revision, drift and protected-data rules stay explicit.','pipe5.title':'Deliver','pipe5.copy':'REST, OAuth MCP, bulk or an enterprise response contract.',
      'object.label':'THE PROPERTY OBJECT','object.title':'The cadastral reference becomes the spine — not the whole story.','object.copy':'A useful Spanish property object can connect the identifiers and evidence around a property while keeping every relationship traceable to its source and authority.','object.cta':'See the identity contract','object.core':'cadastral reference','object.cp':'parcel + geometry','object.ad':'official address','object.bu':'building relations','object.mun':'municipality + authority','object.prov':'source + revision','object.cov':'coverage state',
      'coverage.eyebrow':'COVERAGE WITHOUT FICTION','coverage.title':'One Spain product.<br>Different cadastral authorities.','coverage.copy':'The Dirección General del Catastro is authoritative across Spain except País Vasco and Navarra. PropData treats that boundary as part of the data contract — not an inconvenience to hide.','coverage.live':'DGC COMMON TERRITORY · CERTIFICATION','coverage.next':'FORAL SYSTEMS · SEPARATE INGEST','coverage.link':'Read the coverage contract →','coverage.dgc':'DGC common territory','coverage.dgcCopy':'Official Catastro parcels, addresses and buildings','coverage.certifying':'CERTIFYING','coverage.separate':'SEPARATE SOURCES','coverage.navarraCopy':'Foral cadastral system','coverage.rule':'PropData rule','coverage.ruleCopy':'Do not substitute a DGC answer for a foral-system property. Route to the correct authority or return explicit unavailability.',
      'sources.eyebrow':'AUTHORITATIVE SOURCE MODEL','sources.title':'Build on the source.<br>Then build what the source does not.','sources.copy':'The moat is not downloading Catastro. It is turning municipality-scoped CP, AD and BU data into a versioned property identity system that software can trust.','sources.cp':'Cadastral Parcels','sources.cpCopy':'Parcel identity, geometry and cadastral zoning context.','sources.ad':'Addresses','sources.adCopy':'Official address identities linked back to cadastral context.','sources.bu':'Buildings','sources.buCopy':'Buildings, building parts and construction geometry where published.','sources.rest':'Property detail','sources.restCopy':'Non-protected property detail resolved only against exact existing parcel identity.','sources.docs':'Source & licence docs','sources.official':'Official DGC INSPIRE',
      'use.eyebrow':'WHAT THIS UNLOCKS','use.title':'Property infrastructure for the products built on top of Spain.','use.copy':'PropData Spain is not trying to replace your application. It removes the country-specific cadastral plumbing underneath it so your team can ship the part customers actually pay for.','use1.title':'PropTech applications','use1.copy':'Resolve Spanish property identity, attach parcel context and build workflows without owning municipality-by-municipality ingestion.','use2.title':'AI property assistants','use2.copy':'Give agents a governed property graph instead of forcing an LLM to infer cadastral truth from web pages.','use3.title':'Mapping & land workflows','use3.copy':'Use promoted parcel geometry, coordinates and cadastral identity as the spatial spine for land-facing products.','use4.title':'Due diligence','use4.copy':'Anchor diligence workflows to the right property, authority, source revision and explicit availability state.','use5.title':'Analytics & enrichment','use5.copy':'Join your proprietary datasets to a deterministic cadastral identity layer without flattening away Spanish source semantics.','use6.title':'Enterprise infrastructure','use6.copy':'Country extracts, white-label delivery, custom endpoints and response contracts for high-volume production systems.','use.learn':'Build on PropData →','use.dataLink':'Explore data delivery →','use.enterprise':'Talk to enterprise →',
      'engineering.eyebrow':'LAUNCH ENGINEERING','engineering.title':'“Close enough” is not a property match.','engineering.copy':'Spain’s source graph contains real-world drift: repeated address identities, changing points, building-to-parcel anomalies and municipality-specific revisions. PropData certifies those conditions before promotion instead of hiding them behind a happy-path API.','eng1.title':'Exact parcel required','eng1.copy':'Property detail is attached only to an existing canonical parcel identity.','eng2.title':'Protected fields excluded','eng2.copy':'No ownership or cadastral value is requested by the open-data launch path.','eng3.title':'Drift is evidence','eng3.copy':'Source geometry and address drift is classified, versioned and governed rather than overwritten.','eng4.title':'Promotion is earned','eng4.copy':'Municipality-scale canaries, reconciliation and zero-regression gates precede production promotion.',
      'cert.label':'LATEST VERIFIED MUNICIPALITY PROOF · 4 SEP 2026','cert.requests':'canonical parcel requests completed','cert.details':'direct property detail records emitted','cert.protected':'protected-field hits','cert.writes':'production writes','cert.link':'Read certification evidence →',
      'developers.eyebrow':'FOR PRODUCT TEAMS','developers.title':'One country scope.<br>Multiple ways into the graph.','developers.copy':'The production contract will follow PropData’s existing delivery model. Spain promotion remains gated until the country graph clears launch certification.','developers.p1':'Address → property identity','developers.p2':'Coordinates → containing parcel context','developers.p3':'Cadastral reference → source property','developers.p4':'Property → geometry + building relationships','developers.docs':'Open Spain docs','developers.dashboard':'Open customer dashboard','developers.codeNote':'Illustrative launch contract. Spain production availability remains certification-gated.',
      'global.eyebrow':'THE GLOBAL PROPERTY LAYER','global.title':'Spain is a country product.<br>PropData is the control plane.','global.copy':'The source systems change by country. The operating model does not: preserve native identity, prove relationships, expose coverage, keep provenance and deliver one governed contract to software.','global.spain':'Catastro · launch certification','global.cta':'Explore the full PropData global network →',
      'launch.eyebrow':'SPAIN · EARLY ACCESS','launch.title':'Build the Spanish product.<br>We’ll handle the cadastral infrastructure.','launch.copy':'Spain is in launch certification now. If your product needs Spanish parcel identity, address resolution, building context, geometry or a custom country workflow, talk to us before general availability.','launch.cta1':'Request early access','launch.cta2':'Book a data call',
      'footer.headline':'Property infrastructure for Spain. Connected to the global PropData graph.','footer.copy':'Country-native property intelligence from PropTechUSA.ai — preserving the official source model while giving product teams one operating contract.','footer.status':'SPAIN LAUNCH CERTIFICATION IN PROGRESS','footer.spain':'Spain','footer.graph':'Property graph','footer.coverage':'Coverage','footer.sources':'Sources','footer.certification':'Certification','footer.useCases':'Use cases','footer.build':'Build','footer.dashboard':'Customer Dashboard','footer.bulk':'Bulk & Data','footer.network':'Global network','footer.all':'All countries →','footer.company':'PropTechUSA.ai','footer.companyHome':'Company','footer.book':'Book a call','footer.official':'Official Spain','footer.boundary':'DGC jurisdiction excludes País Vasco and Navarra.','footer.truth':'Truthful nulls · explicit coverage · source provenance · no cross-authority fabrication'
    },
    es: {
      'utility.network':'RED DE INTELIGENCIA INMOBILIARIA DE PROPTECHUSA.AI','utility.status':'ESPAÑA · CERTIFICACIÓN EN CURSO',
      'nav.product':'Producto','nav.data':'Datos de España','nav.developers':'Desarrolladores','nav.network':'Red global','nav.docs':'Docs','nav.dashboard':'Panel','nav.access':'Acceso anticipado',
      'mega.productLabel':'GRAFO INMOBILIARIO DE ESPAÑA','mega.graph':'Grafo inmobiliario','mega.graphCopy':'Identidad, direcciones, edificios y geometría parcelaria.','mega.arch':'Arquitectura','mega.archCopy':'Cómo los datos oficiales se convierten en infraestructura gobernada.','mega.controlLabel':'CAPA DE CONTROL','mega.governance':'Gobernanza','mega.governanceCopy':'Identidad fail-closed, evidencia de deriva y controles de promoción.','mega.useCases':'Casos de uso','mega.useCasesCopy':'Producto, IA, mapas, diligencia y flujos empresariales.',
      'mega.coverageLabel':'MODELO DE AUTORIDAD','mega.coverage':'Cobertura','mega.coverageCopy':'Territorio común DGC y sistemas forales separados.','mega.sources':'Fuentes','mega.sourcesCopy':'Catastro CP, AD, BU y detalle no protegido.','mega.identityLabel':'IDENTIDAD','mega.refcatCopy':'Uniones duraderas por referencia catastral.','mega.protected':'Límite de datos protegidos','mega.protectedCopy':'Titularidad y valor catastral individualizado quedan fuera del contrato abierto.',
      'mega.docs':'Docs de España','mega.docsCopy':'Contrato del país, rutas, identidad y cobertura.','mega.restCopy':'Entrega PropData en servidor con country=ES.','mega.dashboard':'Panel de cliente','mega.dashboardCopy':'Claves, uso, Request Lab, MCP y facturación.','mega.mcpCopy':'Acceso nativo para IA mediante flujo OAuth separado.','mega.spainStatus':'Catastro · certificando','mega.allCountries':'Explorar cobertura global →',
      'hero.status':'CERTIFICACIÓN DE LANZAMIENTO DE ESPAÑA EN CURSO','hero.eyebrow':'PROPDATA ESPAÑA · INFRAESTRUCTURA INMOBILIARIA NATIVA DEL PAÍS','hero.title':'El Catastro de España,<br>normalizado para software.','hero.lede':'PropData está convirtiendo parcelas catastrales, direcciones, edificios y referencias catastrales oficiales en un único grafo inmobiliario determinista para equipos de producto, sistemas de IA y flujos empresariales.','hero.cta1':'Explorar el grafo de España','hero.cta2':'Leer la documentación',
      'proof.label':'ESCALA DEL SISTEMA FUENTE','proof.records':'bienes inmuebles oficiales administrados por la DGC','proof.families':'parcelas · direcciones · edificios','proof.crs':'referencia espacial nativa de la fuente','proof.id':'identidad por referencia catastral','proof.governance':'resolución gobernada','proof.note':'78,9 M es la escala oficial del sistema de la DGC; no implica que todos los registros ya estén promovidos en PropData.',
      'signal.common':'Certificación del territorio común','signal.foral':'Sistemas forales tratados por separado',
      'platform.eyebrow':'EL PRODUCTO','platform.title':'Las rutas son la puerta.<br>El grafo inmobiliario español es el producto.','platform.copy':'España no es un fichero plano de parcelas. Una capa inmobiliaria útil debe conservar la referencia catastral, el contexto municipal, las direcciones, la geometría, las relaciones con edificios, las revisiones de fuente y los estados de cobertura sin inventar datos protegidos o no disponibles.',
      'cap1.title':'Identidad catastral','cap1.copy':'Resolver y conservar la referencia catastral como identificador inmobiliario duradero.','cap2.title':'Grafo de direcciones','cap2.copy':'Vincular direcciones oficiales del Catastro sin perder la semántica de origen.','cap3.title':'Geometría parcelaria','cap3.copy':'Conservar límites catastrales oficiales con su fuente, revisión y contrato espacial.','cap4.title':'Relaciones de edificios','cap4.copy':'Conectar edificios y partes de edificios con la identidad catastral cuando la fuente lo soporte.','cap5.title':'Resolución por coordenadas','cap5.copy':'Convertir latitud y longitud en contexto inmobiliario solo cuando la geometría promovida permita una respuesta determinista.','cap6.title':'Enrutamiento municipal','cap6.copy':'Normalizar miles de paquetes municipales detrás de un único contrato de país.','cap7.title':'Procedencia','cap7.copy':'Mantener familia de fuente, municipio, revisión y trazabilidad junto a cada dato.','cap8.title':'Límite de datos protegidos','cap8.copy':'Titularidad y valor catastral quedan fuera del contrato abierto salvo fuente legal y habilitación separada.','cap9.title':'Semántica de cobertura','cap9.copy':'Coincidencia de inmueble, coincidencia geométrica y cobertura son señales distintas.','cap10.title':'Controles de calidad','cap10.copy':'La ambigüedad, la deriva de fuente y la identidad no resuelta fallan de forma cerrada.','cap11.title':'Entrega para IA','cap11.copy':'El mismo grafo gobernado puede servir REST, OAuth MCP, bulk y flujos empresariales a medida.','cap12.title':'Plano de control del país','cap12.copy':'España utiliza el mismo modelo operativo PropData que EE. UU., Reino Unido, Nueva Zelanda, Australia y Estonia.',
      'architecture.eyebrow':'DEL CATASTRO A INFRAESTRUCTURA DE PRODUCTO','architecture.title':'Una petición inmobiliaria.<br>Una cadena gobernada por debajo.','architecture.copy':'Lo difícil no es servir JSON. Es enrutar a la autoridad correcta, conservar la identidad nativa, unir fuentes oficiales, clasificar la deriva y devolver solo los hechos que soporta la evidencia.',
      'pipe1.title':'Resolver entrada','pipe1.copy':'Dirección, coordenadas o identidad catastral entran en un único contrato de país.','pipe2.title':'Enrutar autoridad','pipe2.copy':'Territorio común DGC o el sistema foral separado correcto.','pipe3.title':'Conectar grafo','pipe3.copy':'REFCAT une parcela, dirección, edificio y contexto no protegido.','pipe4.title':'Gobernar evidencia','pipe4.copy':'Cobertura, revisión, deriva y reglas de datos protegidos siguen explícitas.','pipe5.title':'Entregar','pipe5.copy':'REST, OAuth MCP, bulk o contrato de respuesta empresarial.',
      'object.label':'EL OBJETO INMOBILIARIO','object.title':'La referencia catastral se convierte en la columna vertebral, no en toda la historia.','object.copy':'Un objeto inmobiliario útil conecta identificadores y evidencia alrededor del inmueble manteniendo cada relación trazable a su fuente y autoridad.','object.cta':'Ver el contrato de identidad','object.core':'referencia catastral','object.cp':'parcela + geometría','object.ad':'dirección oficial','object.bu':'relaciones de edificios','object.mun':'municipio + autoridad','object.prov':'fuente + revisión','object.cov':'estado de cobertura',
      'coverage.eyebrow':'COBERTURA SIN FICCIÓN','coverage.title':'Un producto para España.<br>Distintas autoridades catastrales.','coverage.copy':'La Dirección General del Catastro es competente en España excepto País Vasco y Navarra. PropData trata ese límite como parte del contrato de datos.','coverage.live':'TERRITORIO COMÚN DGC · CERTIFICACIÓN','coverage.next':'SISTEMAS FORALES · INGESTA SEPARADA','coverage.link':'Leer el contrato de cobertura →','coverage.dgc':'Territorio común DGC','coverage.dgcCopy':'Parcelas, direcciones y edificios oficiales del Catastro','coverage.certifying':'CERTIFICANDO','coverage.separate':'FUENTES SEPARADAS','coverage.navarraCopy':'Sistema catastral foral','coverage.rule':'Regla PropData','coverage.ruleCopy':'Nunca sustituir una respuesta foral por una respuesta DGC. Enrutar a la autoridad correcta o devolver indisponibilidad explícita.',
      'sources.eyebrow':'MODELO DE FUENTE OFICIAL','sources.title':'Construir sobre la fuente.<br>Y después construir lo que falta.','sources.copy':'La ventaja no es descargar Catastro. Es convertir CP, AD y BU municipales en un sistema versionado de identidad inmobiliaria en el que el software pueda confiar.','sources.cp':'Parcelas catastrales','sources.cpCopy':'Identidad, geometría y contexto de zonificación catastral.','sources.ad':'Direcciones','sources.adCopy':'Identidades oficiales de dirección vinculadas al contexto catastral.','sources.bu':'Edificios','sources.buCopy':'Edificios, partes y geometría constructiva cuando se publica.','sources.rest':'Detalle del inmueble','sources.restCopy':'Detalle no protegido resuelto únicamente contra una identidad parcelaria existente y exacta.','sources.docs':'Docs de fuente y licencia','sources.official':'DGC INSPIRE oficial',
      'use.eyebrow':'LO QUE DESBLOQUEA','use.title':'Infraestructura inmobiliaria para los productos construidos sobre España.','use.copy':'PropData España no intenta reemplazar tu aplicación. Elimina la fontanería catastral específica del país para que tu equipo pueda construir lo que realmente paga el cliente.','use1.title':'Aplicaciones PropTech','use1.copy':'Resuelve identidad inmobiliaria, añade contexto parcelario y construye flujos sin mantener una ingesta municipio por municipio.','use2.title':'Asistentes inmobiliarios de IA','use2.copy':'Da a los agentes un grafo gobernado en vez de obligar a un LLM a inferir verdad catastral desde páginas web.','use3.title':'Mapas y flujos de suelo','use3.copy':'Usa geometría parcelaria promovida, coordenadas e identidad catastral como columna espacial del producto.','use4.title':'Due diligence','use4.copy':'Ancla la diligencia al inmueble, autoridad, revisión de fuente y estado de disponibilidad correctos.','use5.title':'Analítica y enriquecimiento','use5.copy':'Une tus datasets propios a una identidad catastral determinista sin borrar la semántica española.','use6.title':'Infraestructura empresarial','use6.copy':'Extractos de país, white-label, endpoints personalizados y contratos para sistemas de alto volumen.','use.learn':'Construir sobre PropData →','use.dataLink':'Explorar entrega de datos →','use.enterprise':'Hablar con enterprise →',
      'engineering.eyebrow':'INGENIERÍA DE LANZAMIENTO','engineering.title':'“Más o menos” no es una coincidencia inmobiliaria.','engineering.copy':'El grafo fuente de España contiene deriva real: identidades de dirección repetidas, puntos que cambian, anomalías edificio-parcela y revisiones municipales. PropData certifica esas condiciones antes de promover datos.','eng1.title':'Parcela exacta obligatoria','eng1.copy':'El detalle del inmueble solo se adjunta a una identidad parcelaria canónica existente.','eng2.title':'Datos protegidos excluidos','eng2.copy':'La ruta abierta no solicita titularidad ni valor catastral.','eng3.title':'La deriva es evidencia','eng3.copy':'La deriva de geometría y dirección se clasifica, versiona y gobierna.','eng4.title':'La promoción se gana','eng4.copy':'Canarios municipales, reconciliación y controles de regresión preceden la promoción.',
      'cert.label':'ÚLTIMA PRUEBA MUNICIPAL VERIFICADA · 4 SEP 2026','cert.requests':'peticiones de parcelas canónicas completadas','cert.details':'registros de detalle directo emitidos','cert.protected':'impactos de campos protegidos','cert.writes':'escrituras en producción','cert.link':'Leer evidencia de certificación →',
      'developers.eyebrow':'PARA EQUIPOS DE PRODUCTO','developers.title':'Un ámbito de país.<br>Múltiples entradas al grafo.','developers.copy':'El contrato de producción seguirá el modelo actual de PropData. España permanece bloqueada hasta superar la certificación de lanzamiento.','developers.p1':'Dirección → identidad inmobiliaria','developers.p2':'Coordenadas → contexto parcelario','developers.p3':'Referencia catastral → inmueble fuente','developers.p4':'Inmueble → geometría + relaciones de edificios','developers.docs':'Abrir docs de España','developers.dashboard':'Abrir panel de cliente','developers.codeNote':'Contrato de lanzamiento ilustrativo. La producción de España sigue sujeta a certificación.',
      'global.eyebrow':'LA CAPA INMOBILIARIA GLOBAL','global.title':'España es un producto de país.<br>PropData es el plano de control.','global.copy':'Los sistemas fuente cambian por país. El modelo operativo no: conservar identidad nativa, demostrar relaciones, exponer cobertura, mantener procedencia y entregar un contrato gobernado al software.','global.spain':'Catastro · certificación de lanzamiento','global.cta':'Explorar toda la red global de PropData →',
      'launch.eyebrow':'ESPAÑA · ACCESO ANTICIPADO','launch.title':'Construye el producto español.<br>Nosotros gestionamos la infraestructura catastral.','launch.copy':'España está en certificación de lanzamiento. Si necesitas identidad parcelaria, resolución de direcciones, edificios, geometría o un flujo de país a medida, habla con nosotros antes de la disponibilidad general.','launch.cta1':'Solicitar acceso anticipado','launch.cta2':'Reservar una llamada',
      'footer.headline':'Infraestructura inmobiliaria para España. Conectada al grafo global de PropData.','footer.copy':'Inteligencia inmobiliaria nativa por país de PropTechUSA.ai, conservando el modelo oficial y dando a los equipos un único contrato operativo.','footer.status':'CERTIFICACIÓN DE LANZAMIENTO DE ESPAÑA EN CURSO','footer.spain':'España','footer.graph':'Grafo inmobiliario','footer.coverage':'Cobertura','footer.sources':'Fuentes','footer.certification':'Certificación','footer.useCases':'Casos de uso','footer.build':'Construir','footer.dashboard':'Panel de cliente','footer.bulk':'Bulk y datos','footer.network':'Red global','footer.all':'Todos los países →','footer.company':'PropTechUSA.ai','footer.companyHome':'Empresa','footer.book':'Reservar llamada','footer.official':'España oficial','footer.boundary':'La competencia DGC excluye País Vasco y Navarra.','footer.truth':'Nulos honestos · cobertura explícita · procedencia de fuente · sin fabricación entre autoridades'
    }
  };

  function setLanguage(lang) {
    const next = copy[lang] ? lang : 'en';
    document.documentElement.lang = next;
    document.documentElement.dataset.lang = next;
    document.querySelectorAll('[data-i18n]').forEach(node => {
      const value = copy[next][node.dataset.i18n];
      if (value !== undefined) node.innerHTML = value;
    });
    langButtons.forEach(button => button.classList.toggle('active', button.dataset.lang === next));
    try { localStorage.setItem('propdata_spain_lang', next); } catch {}
    document.title = next === 'es'
      ? 'PropData España | API de inteligencia catastral'
      : 'PropData Spain | Catastro Property Intelligence API';
  }

  function closeAllGroups(except = null) {
    navGroups.forEach(group => {
      if (group !== except) group.removeAttribute('open');
    });
  }

  navGroups.forEach(group => {
    group.addEventListener('toggle', () => {
      if (group.open) closeAllGroups(group);
    });
  });

  menu?.addEventListener('click', () => {
    const open = nav?.classList.toggle('open');
    menu.setAttribute('aria-expanded', open ? 'true' : 'false');
    if (!open) closeAllGroups();
  });

  nav?.querySelectorAll('a').forEach(link => link.addEventListener('click', () => {
    nav.classList.remove('open');
    menu?.setAttribute('aria-expanded', 'false');
    closeAllGroups();
  }));

  document.addEventListener('click', event => {
    if (!event.target.closest('.nav-group')) closeAllGroups();
  });

  document.addEventListener('keydown', event => {
    if (event.key === 'Escape') {
      closeAllGroups();
      nav?.classList.remove('open');
      menu?.setAttribute('aria-expanded', 'false');
    }
  });

  langButtons.forEach(button => button.addEventListener('click', () => setLanguage(button.dataset.lang)));

  let initial = 'en';
  try {
    initial = localStorage.getItem('propdata_spain_lang') ||
      (navigator.language?.toLowerCase().startsWith('es') ? 'es' : 'en');
  } catch {}
  setLanguage(initial);
})();
